  ---------------------------------------------------------------------------------
--SCRIPT DE ACTUALIZACION BD A VERSION: 0124
--
--IMPORTANTE: SOLAMENTE EJECUTAR ESTE SCRIPT SOBRE UNA BD CON ESTRUCTURA 0123
--
--GENERA FICHERO LOG SQLUPD_0124.LOG
---------------------------------------------------------------------------------

SPOOL SQLUPD_0124.LOG
SET ECHO ON
SET TIMING ON

-----------------------------------INICIO MODIFICACIONES
  
  CREATE TABLE "DISINP" 
   (	"COD" NUMBER(9,0) NOT NULL ENABLE, 
	"MOMCRE" DATE DEFAULT SYSDATE, 
	"MOMLEC" DATE, 
	"RECMAQREF" CHAR(10 BYTE) NOT NULL ENABLE, 
	"SEC" NUMBER(9,0) NOT NULL ENABLE, 
	"CON" VARCHAR2(1120 BYTE) NOT NULL ENABLE, 
	"MSG" VARCHAR2(160 BYTE) NOT NULL ENABLE, 
	"OPC" VARCHAR2(160 BYTE) NOT NULL ENABLE, 
	"INP" VARCHAR2(80 BYTE), 
	 CONSTRAINT "DISINP_PK" PRIMARY KEY ("COD"));
    
    
   COMMENT ON COLUMN "DISINP"."COD" IS 'Codigo Identificador';
   COMMENT ON COLUMN "DISINP"."MOMCRE" IS 'Momento de creacion';
   COMMENT ON COLUMN "DISINP"."MOMLEC" IS 'Momento de lectura';
   COMMENT ON COLUMN "DISINP"."RECMAQREF" IS 'Referencia Recurso Maquina';
   COMMENT ON COLUMN "DISINP"."SEC" IS 'Secuencia';
   COMMENT ON COLUMN "DISINP"."CON" IS 'Contenido';
   COMMENT ON COLUMN "DISINP"."MSG" IS 'Mensaje';
   COMMENT ON COLUMN "DISINP"."OPC" IS 'Opciones';
   COMMENT ON COLUMN "DISINP"."INP" IS 'Input esperado';
   
   
   
  CREATE TABLE "DISOUT" 
   (	"COD" NUMBER(9,0) NOT NULL ENABLE, 
	"MOMCRE" DATE DEFAULT SYSDATE,
	"MOMLEC" DATE, 
	"RECMAQREF" CHAR(10 BYTE) NOT NULL ENABLE, 
	"SEC" NUMBER(9,0) NOT NULL ENABLE, 
	"SEL" NUMBER(9,0) NOT NULL ENABLE, 
	"OUT" VARCHAR2(80 BYTE), 
	 CONSTRAINT "DISOUT_PK" PRIMARY KEY ("COD")) ;
 

   COMMENT ON COLUMN "DISOUT"."COD" IS 'Codigo Identificador';
   COMMENT ON COLUMN "DISOUT"."MOMCRE" IS 'Momento de creacion';
   COMMENT ON COLUMN "DISOUT"."MOMLEC" IS 'Momento de lectura';
   COMMENT ON COLUMN "DISOUT"."RECMAQREF" IS 'Referencia Recurso Maquina';
   COMMENT ON COLUMN "DISOUT"."SEC" IS 'Secuencia';
   COMMENT ON COLUMN "DISOUT"."SEL" IS 'Seleccion (opcion)';
   COMMENT ON COLUMN "DISOUT"."OUT" IS 'Output (entrada del usuario)';
 
 
 
 -----------------------------------FIN MODIFICACIONES

UPDATE VERSIONES SET VERSION='0124', MOMENTO=SYSDATE WHERE SOFCOD='BD';
COMMIT;

SPOOL OFF;

EXIT;

--FIN DEL SCRIPT DE ACTUALIZACION