runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v CLIENTE /d \"ppov3\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_DRIVE /d \"C:\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_HOME /d \"C:\home\ppov3\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_BIN /d \"C:\home\ppov3\bin\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_SO /d \"WINDOWS\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_CHARSET /d \"ISO\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_INTERNACIONAL /d \"NO\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_IDIOMA /d \"SPA\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_TRAZA /d \"4\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_VERSION /d \"a0000\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_LICENCIA /d \"ppov3\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_TMP /d \"C:\home\ppov3\tmp\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_TMPOLD /d \"C:\home\ppov3\tmpold\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_TRASP /d \"C:\home\ppov3\tmpint\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_A_GESTION /d \"C:\home\ppov3\a_gestion\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_DE_GESTION /d \"C:\home\ppov3\de_gestion\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_SPW /d \"C:\Speedware\SPW\V713\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_STD_HOME /d \"C:\home\adaia3\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v DB_USUARIO /d \"ppov3\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v DB_PASSWD /d \"ppov3\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v PATH /d \"C:\Speedware\SPW\V713\bin;C:\home\ppov3\bin;C:\home\bin;C:\UNIXUTIL\iconv\;C:\oracle\product\11.2.0\client_1\bin;C:\oracle\product\11.2.0\client_1\;C:\Program Files\HP\NCU;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\SysTools;C:\Program Files\HP OpenView\lib;C:\Program Files\HP OpenView\bin;C:\Program Files\HP OpenView\bin\win64;C:\Program Files\HP OpenView\bin\win64\OpC;C:\Program Files\OmniBack\bin\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v SPW_BIN /d \"C:\Speedware\SPW\V713\bin\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v SPW_BIN_713 /d \"C:\Speedware\SPW\V713\bin\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v SPW_HOME /d \"C:\Speedware\SPW\V713\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v m4glmgo /d \"C:\Speedware\SPW\V713\PUB\m4glmgo.SPA\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v msysmgo /d \"C:\Speedware\SPW\V713\PUB\msysmgo.SPA\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v mutlmgo /d \"C:\Speedware\SPW\V713\PUB\mutlmgo.SPA\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v medimgo /d \"C:\Speedware\SPW\V713\PUB\medimgo.SPA\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v NLS_LANG /d \"AMERICAN_AMERICA.WE8MSWIN1252\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v WINZIP /d \"C:\Program Files\IZArc\IZarce.exe\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v TEMP /d \"C:\home\ppov3\tmpspw\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v TMP /d \"C:\home\ppov3\tmpspw\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v OS_VERSION /d \"2008\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ENTORNO /d \"DESAROLLO\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_WWW /d \"C:\tomcat\webapps\ppov3\" /f"
runas /profile /user:svcppov3  /savecred "reg add HKCU\Environment /v ADAIA_BIRT /d \"http://172.20.10.66:8080/birt-ppov3"